backend:
  name: git-gateway
  repo: ReadWithAudrey/readwithaudrey
  branch: markdown # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads"

collections:
  - label: "Welcome Page"
    name: "welcome page"
    delete: false
    files:
      - label: "Testimonials"
        name: "testimonials"
        file: src/markdown/testimonials.md
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Testimonials", options:["Testimonials"], }
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Footer", name: "footer", widget: "string"}
          - {label: "Main text", name: "body", widget: "markdown"}
