backend:
  name: git-gateway
  repo: ReadWithAudrey/readwithaudrey
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads"

collections:
  - label: "Forms"
    name: "forms"
    files:
      - label: "Form 1"
        name: "Form1"
        file: src/markdown/formPart1.md
        fields:
          - {label: "Title", name: "title", widget:"select", required: true, options: ["Form Part 1"]}
          - {label: "Question 1", name: "q1", widget: "string", required:true}
          - {label: "Question 2", name: "q2", widget: "string", required:true}
          - {label: "Question 3", name: "q3", widget: "string", required:true}
