---
backend:
  name: git-gateway
  repo: ReadWithAudrey/readwithaudrey
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: src/markdown/notfound.md
        label: "404 Page"
        name: "notfound"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "404", options: ["404"] }
          - {label: "Header", name: "header1", widget: "string"}
          - {label: "Paragraph 1", name: "p1", widget: "string"}
      - file: src/markdown/thankyoucontact.md
        label: "Thank You (Contact)"
        name: "thankyoucontact"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Thank You Contact", options: ["Thank You Contact"] }
          - {label: "Header", name: "header1", widget: "string"}
          - {label: "Paragraph 1", name: "p1", widget: "string"}
          - {label: "Main text", name: "body", widget: "markdown"}
      - file: src/markdown/faq.md
        label: "FAQs"
        name: "faqs"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "FAQs", options: ["FAQs"] }
          - {label: "Footer", name: "footer", widget: "string"}
          - {label: "Main text", name: "body", widget: "markdown"}
      - file: src/markdown/why.md
        label: "Our Why"
        name: "ourwhy"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Our Why", options: ["Our Why"] }
          - {label: "Main text", name: "body", widget: "markdown"}
      - file: src/markdown/terms.md
        label: "Terms"
        name: "terms"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Terms", options: ["Terms"] }
          - {label: "Main text", name: "body", widget: "markdown"}
      - file: src/markdown/privacy.md
        label: "Privacy"
        name: "privacy"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Privacy", options: ["Privacy"] }
          - {label: "Main text", name: "body", widget: "markdown"}
      - file: src/markdown/thankyou.md
        label: "Thank You"
        name: "thankyou"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Thank You", options: ["Thank You"] }
          - {label: "Header 1", name: "header1", widget: "string"}
          - {label: "Header 2", name: "header2", widget: "string"}
          - {label: "p1", name: "p1", widget: "string"}
          - {label: "p2", name: "p2", widget: "string"}
          - {label: "p3", name: "p3", widget: "string"}
          - {label: "p4", name: "p4", widget: "string"}
          - {label: "shareUrl", name: "shareUrl", widget: "string"}
          - {label: "twitterText", name: "twitterText", widget: "string"}
          - {label: "facebookText", name: "facebookText", widget: "string"}
          - {label: "emailBody", name: "emailBody", widget: "string"}
          - {label: "emailSubject", name: "emailSubject", widget: "string"}
          - {label: "Main text", name: "body", widget: "markdown"}
      - file: src/markdown/contact.md
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Contact", options: ["Contact"] }
          - {label: "Header 1", name: "header1", widget: "string"}
          - {label: "p1", name: "p1", widget: "string"}
          - {label: "Main text", name: "body", widget: "markdown"}
  - name: "welcome page"
    label: "Welcome Page"
    files:
      - file: src/markdown/about.md
        label: "About Audrey"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "About Audrey", options: ["About Audrey"] }
          - {label: "Header 1", name: "header1", widget: "string"}
          - {label: "Text 1", name: "text1", widget: "string"}
          - {label: "Header 2", name: "header2", widget: "string"}
          - {label: "Text 2", name: "text2", widget: "string"}
          - {label: "Header 3", name: "header3", widget: "string"}
          - {label: "Text 3", name: "text3", widget: "string"}
      - file: src/markdown/howitworks.md
        label: "How It Works"
        name: "howitworks"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "How It Works", options: ["How It Works"] }
          - {label: "Header", name: "header", widget: "string"}
          - {label: "p1", name: "p1", widget: "string"}
          - {label: "p2", name: "p2", widget: "string"}
          - {label: "p3", name: "p3", widget: "string"}
      - file: src/markdown/example.md
        label: "Examples"
        name: "example"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Examples", options: ["Examples"] }
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Footer", name: "footer", widget: "string"}
          - {label: "Main text", name: "body", widget: "markdown"}
      - file: src/markdown/testimonials.md
        label: "Testimonials"
        name: "testimonial"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Testimonials", options:["Testimonials"], }
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Footer", name: "footer", widget: "string"}
          - {label: "Main text", name: "body", widget: "markdown"}
  - name: "forms"
    label: "Forms"
    files:
      - file: src/markdown/formpartone.md
        label: "Form 1"
        name: "formone"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Form 1", options: ["Form 1"]}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "description", name: "description", widget: "string"}
          - {label: "q1", name: "q1", widget: "string"}
          - {label: "q1 placeholder", name: "q1Placeholder", widget: "string"}
          - {label: "q2", name: "q2", widget: "string"}
          - {label: "q2 placeholder", name: "q2Placeholder", widget: "string"}
          - {label: "q3", name: "q3", widget: "string"}
          - {label: "q3 placeholder", name: "q3Placeholder", widget: "string"}
          - {label: "finalText", name: "finalText", widget: "string"}
      - file: src/markdown/formparttwo.md
        label: "Form 2"
        name: "formtwo"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Form 2", options: ["Form 2"]}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "description", name: "description", widget: "string"}
          - {label: "q1", name: "q1", widget: "string"}
          - {label: "q1 placeholder", name: "q1Placeholder", widget: "string"}
          - {label: "q2", name: "q2", widget: "string"}
          - {label: "readListen1", name: "readListen1", widget: "string"}
          - {label: "readListen2", name: "readListen2", widget: "string"}
          - {label: "readListen3", name: "readListen3", widget: "string"}
          - {label: "q3", name: "q3", widget: "string"}
          - {label: "q4", name: "q4", widget: "string"}
          - {label: "q5", name: "q5", widget: "string"}
          - {label: "bookType1", name: "bookType1", widget: "string"}
          - {label: "bookType2", name: "bookType2", widget: "string"}
          - {label: "bookType3", name: "bookType3", widget: "string"}
      - file: src/markdown/formpartthree.md
        label: "Form 3"
        name: "formthree"
        fields:
          - {label: "Title", name: "title", widget: "select", default: "Form 3", options: ["Form 3"]}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "description", name: "description", widget: "string"}
          - {label: "q1", name: "q1", widget: "string"}
          - {label: "q1 placeholder", name: "q1Placeholder", widget: "string"}
          - {label: "q2", name: "q2", widget: "string"}
          - {label: "q2 placeholder", name: "q2Placeholder", widget: "string"}
          - {label: "Tips", name: "tips", widget: "string"}
